// Generated by generate.py from frozen sources. Do not edit directly.
#pragma once
#include "../r1_tworoads_20260917/stream/stream.hpp"
#include <boost/multiprecision/cpp_int.hpp>
#include <type_traits>

namespace fullrange {
using namespace allsize;
using boost::multiprecision::cpp_int;
template<class Count> struct Wide;
template<> struct Wide<uint64_t> { using type=unsigned __int128; };
template<> struct Wide<unsigned __int128> { using type=boost::multiprecision::uint256_t; };
template<> struct Wide<boost::multiprecision::uint256_t> { using type=boost::multiprecision::uint512_t; };
template<> struct Wide<boost::multiprecision::uint512_t> { using type=boost::multiprecision::uint1024_t; };

template<class Count> struct Kernel {
    using Wider=typename Wide<Count>::type;
    using Extra=orderdp::Extra;
    inline static const Count infinity=std::numeric_limits<Count>::max();
    struct Data { std::vector<Count> core; allsize::Work work; size_t state_bytes=0; double peel_ms=0; };
    struct Common { Data data; tworoads::Statistics stats; };
    struct Result { Common common; Extra extra; };
    static void checked_add(Count& a,Count b) {
        if (b>=infinity-a) throw std::overflow_error("selected count width insufficient");
        a+=b;
    }
class Heap {
    Vertices heap_, position_;
    std::vector<Count>& keys_;
    bool less(Vertex a, Vertex b) const {
        return keys_[a] < keys_[b] || (keys_[a] == keys_[b] && a < b);
    }
    void swap_at(size_t a, size_t b) {
        std::swap(heap_[a], heap_[b]);
        position_[heap_[a]] = static_cast<Vertex>(a);
        position_[heap_[b]] = static_cast<Vertex>(b);
    }
    void down(size_t at) {
        while (2 * at + 1 < heap_.size()) {
            size_t child = 2 * at + 1;
            if (child + 1 < heap_.size() && less(heap_[child + 1], heap_[child])) ++child;
            if (!less(heap_[child], heap_[at])) break;
            swap_at(at, child); at = child;
        }
    }
public:
    explicit Heap(std::vector<Count>& keys): heap_(keys.size()), position_(keys.size()), keys_(keys) {
        std::iota(heap_.begin(), heap_.end(), 0);
        std::iota(position_.begin(), position_.end(), 0);
        for (size_t i = heap_.size() / 2; i; --i) down(i - 1);
    }
    bool empty() const { return heap_.empty(); }
    Vertex first() const { return heap_.front(); }
    bool contains(Vertex v) const { return position_[v] != absent; }
    Vertex pop() {
        Vertex v = heap_.front();
        swap_at(0, heap_.size() - 1);
        heap_.pop_back(); position_[v] = absent;
        if (!heap_.empty()) down(0);
        return v;
    }
    void decrease(Vertex v, Count value) {
        require(contains(v) && value <= keys_[v], "invalid heap decrease");
        keys_[v] = value;
        size_t at = position_[v];
        while (at && less(heap_[at], heap_[(at - 1) / 2])) {
            size_t parent = (at - 1) / 2;
            swap_at(at, parent); at = parent;
        }
    }
};

class Combinations {
    int columns_;
    std::vector<Count> values_;
public:
    Combinations(Vertex maximum, int s): columns_(s + 1),
        values_((static_cast<size_t>(maximum) + 1) * static_cast<size_t>(s + 1), 0) {
        const size_t columns = static_cast<size_t>(columns_);
        for (Vertex n = 0; n <= maximum; ++n) {
            values_[static_cast<size_t>(n) * columns] = 1;
            for (int k = 1; k <= s && static_cast<Vertex>(k) <= n; ++k) {
                const size_t col = static_cast<size_t>(k);
                Count a = values_[static_cast<size_t>(n - 1) * columns + col - 1];
                Count b = values_[static_cast<size_t>(n - 1) * columns + col];
                values_[static_cast<size_t>(n) * columns + col] =
                    (a >= infinity - b) ? infinity : a + b;
            }
        }
    }
    Count operator()(int n, int k) const {
        if (k < 0 || k > n || n < 0) return 0;
        require(k < columns_, "combination column out of range");
        size_t i = static_cast<size_t>(n) * static_cast<size_t>(columns_) + static_cast<size_t>(k);
        require(i < values_.size(), "combination row out of range");
        if (values_[i] == infinity) throw std::overflow_error("binomial coefficient exceeds uint64");
        return values_[i];
    }
};


    static Count contribution(const Layout& index,size_t p,bool pivot,int s,int live,const Combinations& choose) {
        return choose(live-static_cast<int>(pivot),s-static_cast<int>(index.paths.holds[p])-static_cast<int>(pivot));
    }
static Count capped_choose(uint64_t n,int r,Count cap,tworoads::Statistics& stats) {
    if (!cap || r<0 || static_cast<uint64_t>(r)>n) return 0;
    r=static_cast<int>(std::min<uint64_t>(r,n-r));
    Wider value=1;
    for (int j=1; j<=r; ++j) {
        ++stats.binomial_steps;
        value=value*(n-j+1)/j;
        if (value>=cap) return cap;
    }
    return static_cast<Count>(std::min<Wider>(cap,value));
}

static Count integer_upper(Count a,int r,Vertex maximum,tworoads::Statistics& stats) {
    Count answer=0;
    uint64_t upper=maximum;
    for (int j=r; j>=1 && a; --j) {
        require(upper>=static_cast<uint64_t>(j),"invalid canonical upper argument");
        uint64_t low=j-1,high=upper+1;
        while (high-low>1) {
            const uint64_t middle=low+(high-low)/2;
            if (capped_choose(middle,j,a+1,stats)<=a) low=middle;
            else high=middle;
        }
        const Count term=capped_choose(low,j,a+1,stats);
        require(term<=a && term>0,"invalid canonical term");
        a-=term;
        const Count next=capped_choose(low,j+1,infinity-1-answer,stats);
        answer+=next;
        if (answer==infinity-1) return answer;
        upper=low-1;
    }
    require(a==0,"incomplete canonical expansion");
    return answer;
}

class Queue {
    struct Item { Count key; Vertex vertex; };
    std::vector<Item> heap_;
    Vertices position_;
    Extra& work_;
    bool less(size_t a,size_t b) {
        ++work_.heap_comparisons;
        const auto& x=heap_[a]; const auto& y=heap_[b];
        return x.key<y.key || (x.key==y.key && x.vertex<y.vertex);
    }
    void swap_at(size_t a,size_t b) {
        std::swap(heap_[a],heap_[b]);
        position_[heap_[a].vertex]=a;
        position_[heap_[b].vertex]=b;
    }
    void up(size_t at) {
        while (at && less(at,(at-1)/2)) {
            const size_t parent=(at-1)/2;
            swap_at(at,parent); at=parent;
        }
    }
    void down(size_t at) {
        while (2*at+1<heap_.size()) {
            size_t child=2*at+1;
            if (child+1<heap_.size() && less(child+1,child)) ++child;
            if (!less(child,at)) break;
            swap_at(child,at); at=child;
        }
    }
public:
    Queue(std::span<const Count> raw,std::span<const Count> upper,bool all,Extra& work)
        : position_(raw.size(),absent),work_(work) {
        size_t size=0;
        for (Vertex v=0; v<raw.size(); ++v) size+=raw[v] && (all || raw[v]<upper[v]);
        heap_.reserve(size);
        for (Vertex v=0; v<raw.size(); ++v) if (raw[v] && (all || raw[v]<upper[v])) {
            position_[v]=heap_.size();
            heap_.push_back({std::min(raw[v],upper[v]),v});
        }
        for (size_t i=heap_.size()/2; i; --i) down(i-1);
        work_.heap_initial+=heap_.size();
        work_.peak_heap=std::max<uint64_t>(work_.peak_heap,heap_.size());
    }
    bool empty() const { return heap_.empty(); }
    bool contains(Vertex v) const { return position_[v]!=absent; }
    Count first_key() const { return empty() ? infinity : heap_.front().key; }
    Count key(Vertex v) const { return heap_[position_[v]].key; }
    Vertex pop() {
        require(!empty(),"pop empty exception queue");
        const Vertex v=heap_.front().vertex;
        swap_at(0,heap_.size()-1); heap_.pop_back(); position_[v]=absent;
        if (!empty()) down(0);
        ++work_.heap_pops;
        return v;
    }
    void insert(Vertex v,Count value) {
        require(!contains(v),"duplicate exception insertion");
        position_[v]=heap_.size(); heap_.push_back({value,v}); up(heap_.size()-1);
        ++work_.heap_inserts;
        work_.peak_heap=std::max<uint64_t>(work_.peak_heap,heap_.size());
    }
    void decrease(Vertex v,Count value) {
        require(contains(v) && value<=key(v),"invalid exception decrease");
        heap_[position_[v]].key=value; up(position_[v]);
        ++work_.heap_decreases;
    }
    size_t bytes() const { return heap_.capacity()*sizeof(Item)+position_.capacity()*sizeof(Vertex); }
    void audit() {
        for (size_t i=0; i<heap_.size(); ++i) {
            require(position_[heap_[i].vertex]==i,"exception handle differs");
            require(!i || !less(i,(i-1)/2),"exception heap order differs");
        }
    }
};

template<bool Stop=false> Data fixed_sparse(const Layout& index, Vertex n, const Combinations& choose, const Vertices& ordinary) {
    const auto start = Clock::now();
    Data result;
    result.core.assign((index.maximum + 1) * static_cast<size_t>(n), 0);
    std::copy(ordinary.begin(), ordinary.end(), result.core.begin() + 2 * static_cast<size_t>(n));
    for (int s = 3; s <= index.maximum; ++s) {
        std::vector<Count> initial(n, 0);
        Vertices pivots(index.paths.size());
        std::vector<uint8_t> alive(index.paths.size(), 0);
        for (size_t p = 0; p < index.paths.size(); ++p) if (index.valid(p, s)) {
            alive[p] = 1;
            pivots[p] = static_cast<Vertex>(index.paths.row(p).size() - index.paths.holds[p]);
            const Count h = contribution(index, p, false, s, pivots[p], choose);
            const Count z = contribution(index, p, true, s, pivots[p], choose);
            for (size_t i = index.paths.off[p]; i < index.paths.off[p + 1]; ++i) {
                ++result.work.count_reads;
                checked_add(initial[index.paths.vertices[i]], index.pivot(i) ? z : h);
            }
        }
        Vertices local(n, absent), original;
        std::vector<Count> degree;
        for (Vertex v = 0; v < n; ++v) if (initial[v]) {
            local[v] = static_cast<Vertex>(degree.size());
            original.push_back(v);
            degree.push_back(initial[v]);
        }
        const size_t preparation_bytes = initial.capacity() * sizeof(Count);
        std::vector<Count>().swap(initial);
        Heap queue(degree);
        result.state_bytes = std::max(result.state_bytes,
            degree.capacity() * sizeof(Count) + pivots.capacity() * sizeof(Vertex) + alive.capacity()
            + (local.capacity() + original.capacity()) * sizeof(Vertex)
            + std::max(preparation_bytes, 2 * degree.size() * sizeof(Vertex)));
        if constexpr (Stop) { if (degree.empty()) break; }
        while (!queue.empty()) {
            const Vertex local_v = queue.pop(), v = original[local_v];
            const Count k = degree[local_v];
            result.core[static_cast<size_t>(s) * n + v] = k;
            ++result.work.events;
            for (Vertex occurrence : index.touching(v)) {
                ++result.work.source_reads;
                const size_t p = index.owner[occurrence];
                if (!alive[p]) continue;
                const int q = pivots[p];
                Count h, z;
                if (index.pivot(occurrence)) {
                    h = contribution(index, p, false, s, q, choose) - contribution(index, p, false, s, q - 1, choose);
                    z = contribution(index, p, true, s, q, choose) - contribution(index, p, true, s, q - 1, choose);
                    --pivots[p];
                } else {
                    h = contribution(index, p, false, s, q, choose);
                    z = contribution(index, p, true, s, q, choose);
                    alive[p] = 0;
                }
                if (!h && !z) continue;
                for (size_t i = index.paths.off[p]; i < index.paths.off[p + 1]; ++i) {
                    ++result.work.target_reads;
                    const Vertex u = local[index.paths.vertices[i]];
                    const Count loss = index.pivot(i) ? z : h;
                    if (u != absent && queue.contains(u) && degree[u] > k && loss) {
                        queue.decrease(u, loss >= degree[u] - k ? k : degree[u] - loss);
                        ++result.work.updates;
                    }
                }
            }
        }
    }
    result.peel_ms = ms(start);
    return result;
}

template<bool Transfer,bool AllHeap=false,bool Audit=false>
Result solve(const Graph& graph,const Layout& index,const Combinations& choose,
             const Vertices& ordinary,const std::vector<Count>* expected=nullptr) {
    const auto start=Clock::now();
    const Vertex n=graph.n;
    Result result;
    auto& data=result.common.data;
    auto& stats=result.common.stats;
    auto& work=data.work;
    auto& extra=result.extra;
    data.core.assign(static_cast<size_t>(index.maximum+1)*n,0);
    std::copy(ordinary.begin(),ordinary.end(),data.core.begin()+2*static_cast<size_t>(n));
    Vertices previous_order(n),next_order;
    std::iota(previous_order.begin(),previous_order.end(),0);
    if (!std::is_sorted(ordinary.begin(),ordinary.end()))
        std::sort(previous_order.begin(),previous_order.end(),[&](Vertex u,Vertex v) {
            return ordinary[u]<ordinary[v] || (ordinary[u]==ordinary[v] && u<v);
        });
    next_order.reserve(n);
    const Vertex maximum=ordinary.empty() ? 0 : *std::max_element(ordinary.begin(),ordinary.end());
    struct Cache { Count key=infinity,value=0; };
    std::vector<Cache> cache(4096);
    for (int s=3; s<=index.maximum; ++s) {
        auto upper=std::span<Count>(data.core).subspan(static_cast<size_t>(s)*n,n);
        const auto previous=std::span<const Count>(data.core).subspan(static_cast<size_t>(s-1)*n,n);
        std::vector<Count> support(n,0),wh(index.paths.size(),0),wp(index.paths.size(),0);
        Vertices count(index.paths.size(),0);
        std::vector<uint8_t> live(n,0),touched(index.paths.size(),0),dead(index.paths.size(),1),dirty(n,0);
        for (size_t p=0; p<index.paths.size(); ++p) if (index.valid(p,s)) {
            dead[p]=0;
            count[p]=index.paths.row(p).size()-index.paths.holds[p];
            wh[p]=contribution(index,p,false,s,count[p],choose);
            wp[p]=contribution(index,p,true,s,count[p],choose);
            for (size_t i=index.paths.off[p]; i<index.paths.off[p+1]; ++i) {
                ++work.count_reads;
                checked_add(support[index.paths.vertices[i]],index.pivot(i) ? wp[p] : wh[p]);
            }
        }
        next_order.clear();
        Vertex remaining=0;
        const auto bounding=Clock::now();
        std::fill(cache.begin(),cache.end(),Cache{});
        for (Vertex v=0; v<n; ++v) {
            if (!support[v]) { next_order.push_back(v); continue; }
            live[v]=1; ++remaining;
            const Count a=Transfer ? previous[v] : ordinary[v];
            Cache& entry=cache[static_cast<size_t>((a^(a>>17)^(a>>37))&(cache.size()-1))];
            if (entry.key!=a) {
                ++stats.cache_misses;
                if constexpr (Transfer) entry={a,integer_upper(a,s-2,maximum,stats)};
                else entry={a,capped_choose(static_cast<uint64_t>(a),s-1,infinity-1,stats)};
            } else ++stats.cache_hits;
            upper[v]=entry.value;
            stats.initial_capped+=upper[v]<support[v];
            require(upper[v]>0,"zero upper bound for a clique member");
            if constexpr (Audit) {
                require(expected && upper[v]>=(*expected)[static_cast<size_t>(s)*n+v],"stream upper below answer");
                if constexpr (Transfer) {
                    const Count ord=capped_choose(ordinary[v],s-1,infinity-1,stats);
                    const Wider ratio=static_cast<Wider>(previous[v])*(ordinary[v]-s+2)/(s-1);
                    require(upper[v]<=ord && upper[v]<=ratio,"Phi is not the combined parent upper");
                }
            }
        }
        stats.bounds_ms+=ms(bounding);
        Queue heap(support,upper,AllHeap,extra);
        Vertices batch,affected,changed;
        size_t cursor=0;
        auto stream_key=[&]() -> Count {
            if constexpr (AllHeap) return infinity;
            while (cursor<previous_order.size() && !live[previous_order[cursor]]) { ++cursor; ++extra.order_reads; }
            return cursor<previous_order.size() ? upper[previous_order[cursor]] : infinity;
        };
        std::vector<uint64_t> cliques;
        if constexpr (Audit) cliques=bottomup::clique_masks(graph,s);
        auto audit=[&] {
            if constexpr (Audit) {
                ++stats.audits;
                uint64_t mask=0;
                for (Vertex v=0; v<n; ++v) if (live[v]) mask|=uint64_t{1}<<v;
                std::vector<Count> actual(n,0);
                for (uint64_t clique : cliques) if ((clique&mask)==clique)
                    for (Vertex v=0; v<n; ++v) if ((clique>>v)&1) ++actual[v];
                Count minimum=infinity,last=0;
                for (Vertex v : previous_order) if (live[v]) {
                    require(upper[v]>=last,"upper stream not sorted"); last=upper[v];
                    require(support[v]==actual[v],"stream raw degree differs");
                    require(heap.contains(v)==(AllHeap || support[v]<upper[v]),"exception membership differs");
                    if (heap.contains(v)) require(heap.key(v)==std::min(upper[v],support[v]),"stored heap key differs");
                    minimum=std::min(minimum,std::min(upper[v],support[v]));
                }
                for (Vertex v=0; v<n; ++v) if (!live[v])
                    require(upper[v]==(*expected)[static_cast<size_t>(s)*n+v],"completed stream output differs");
                require(minimum==std::min(stream_key(),heap.first_key()),"two-stream minimum differs");
                heap.audit();
            }
        };
        auto memory=[&] {
            data.state_bytes=std::max(data.state_bytes,(support.capacity()+wh.capacity()+wp.capacity())*sizeof(Count)
                +(count.capacity()+batch.capacity()+affected.capacity()+changed.capacity()+previous_order.capacity()+next_order.capacity())*sizeof(Vertex)
                +live.capacity()+touched.capacity()+dead.capacity()+dirty.capacity()+heap.bytes()+cache.capacity()*sizeof(Cache));
        };
        audit(); memory();
        if (!remaining) { extra.skipped_layers=index.maximum-s; break; }
        Count level=0;
        while (remaining) {
            ++stats.batches;
            level=std::max(level,std::min(stream_key(),heap.first_key()));
            require(level!=infinity,"unfinished stream without a minimum");
            batch.clear();
            while (std::min(stream_key(),heap.first_key())<=level) {
                Vertex v;
                if (heap.first_key()<=level) v=heap.pop();
                else {
                    require(cursor<previous_order.size(),"exhausted upper stream");
                    v=previous_order[cursor++]; ++extra.order_reads; ++extra.implicit_pops;
                    require(!heap.contains(v),"implicit removal still in heap");
                }
                require(live[v],"duplicate stream removal");
                live[v]=0; --remaining;
                stats.early_removals+=support[v]>level;
                upper[v]=level;
                next_order.push_back(v); batch.push_back(v); ++work.events;
            }
            if (!remaining) { audit(); memory(); break; }
            affected.clear(); changed.clear();
            for (Vertex v : batch) for (Vertex occurrence : index.touching(v)) {
                ++work.source_reads;
                const size_t p=index.owner[occurrence];
                if (dead[p]) continue;
                if (!touched[p]) { touched[p]=1; affected.push_back(p); }
                if (index.pivot(occurrence)) { require(count[p]>0,"negative stream optional count"); --count[p]; }
                else dead[p]=1;
            }
            for (Vertex p : affected) {
                if (count[p]<static_cast<Vertex>(s)-index.paths.holds[p]) dead[p]=1;
                const Count next_h=dead[p] ? 0 : contribution(index,p,false,s,count[p],choose);
                const Count next_p=dead[p] ? 0 : contribution(index,p,true,s,count[p],choose);
                require(next_h<=wh[p] && next_p<=wp[p],"negative stream path loss");
                const Count loss_h=wh[p]-next_h,loss_p=wp[p]-next_p;
                wh[p]=next_h; wp[p]=next_p; touched[p]=0;
                if (!loss_h && !loss_p) continue;
                for (size_t i=index.paths.off[p]; i<index.paths.off[p+1]; ++i) {
                    ++work.target_reads;
                    const Count delta=index.pivot(i) ? loss_p : loss_h;
                    const Vertex v=index.paths.vertices[i];
                    if (!delta || !live[v]) continue;
                    require(support[v]>=delta,"stream raw degree underflow");
                    support[v]-=delta;
                    if (!dirty[v]) { dirty[v]=1; changed.push_back(v); }
                }
            }
            for (Vertex v : changed) {
                dirty[v]=0;
                const Count next=std::min(upper[v],support[v]);
                if (heap.contains(v)) {
                    if (next<heap.key(v)) { heap.decrease(v,next); ++work.updates; }
                    else ++stats.unchanged_keys;
                } else if (support[v]<upper[v]) { heap.insert(v,next); ++work.updates; }
                else ++stats.unchanged_keys;
            }
            audit(); memory();
        }
        require(next_order.size()==n,"incomplete next-layer order");
        if constexpr (Audit)
            for (size_t i=1; i<next_order.size(); ++i)
                require(upper[next_order[i-1]]<=upper[next_order[i]],"next core order differs");
        if constexpr (Transfer) previous_order.swap(next_order);
    }
    data.peel_ms=ms(start);
    return result;
}
};
}
