#!/usr/bin/env python3
"""
probe_region_ie.py — standalone probe for the "fuse CPI into Region/Class"
idea (SigmodPlus section 24, tasks #137-138). Touches NO existing code.

It tests whether the s-clique support of an r-clique can be computed by
inclusion-exclusion (IE) over its host maximal cliques (regions),
instead of by CPI pivot paths:

    sup(R0) = | { S : R0 subset S, |S|=s, S a clique } |
            = sum_{empty != A subset H} (-1)^{|A|+1} C(|cap_{M in A} M| - r, s - r)

where H = { maximal cliques M : R0 subset M } and the intersection sizes
come straight from the region (maximal-clique) structure that the
Region/Class quotient already encodes.

For each sampled r-clique it reports:
  (1) CORRECTNESS: region-IE value vs the ground-truth count of
      s-cliques containing R0 (direct enumeration over the common
      neighbourhood). On small graphs these must match exactly; that is
      the same number CPI computes.
  (2) COST: |H| (raw IE would be 2^|H|) and the size of the
      meet-closure of H (the realistic IE term count after merging
      equal region intersections / dominance). Small closure => fusion
      is cheap on this graph; blow-up => the CPI partition is earning
      its keep (expected only on heavy-overlap graphs like ca-HepPh,
      already our one weak case).

Usage:
  python3 scripts/probe_region_ie.py graphs/dblp-core30.edges 3 4 --sample 200
  python3 scripts/probe_region_ie.py graphs/ca-GrQc.edges 4 5 --sample 200 --no-correctness
"""
from __future__ import annotations
import argparse, itertools, math, random, sys, time
from math import comb


def load_graph(path):
    adj = {}
    with open(path) as f:
        first = f.readline().split()
        n = int(first[0])
        for v in range(n):
            adj[v] = set()
        for line in f:
            p = line.split()
            if len(p) < 2:
                continue
            u, v = int(p[0]), int(p[1])
            if u == v:
                continue
            adj.setdefault(u, set()).add(v)
            adj.setdefault(v, set()).add(u)
    return adj


def maximal_cliques(adj, min_size, time_budget):
    """Bron-Kerbosch with pivoting; returns maximal cliques of size>=min_size
    as frozensets. Aborts (returns None) if it exceeds time_budget seconds."""
    sys.setrecursionlimit(10000)
    out = []
    t0 = time.time()
    aborted = [False]

    def bk(R, P, X):
        if aborted[0]:
            return
        if time.time() - t0 > time_budget:
            aborted[0] = True
            return
        if not P and not X:
            if len(R) >= min_size:
                out.append(frozenset(R))
            return
        PX = P | X
        # pivot maximising |P ∩ N(u)|
        u = max(PX, key=lambda u: len(P & adj[u]))
        for v in list(P - adj[u]):
            bk(R | {v}, P & adj[v], X & adj[v])
            P.discard(v)
            X.add(v)

    bk(set(), set(adj.keys()), set())
    return None if aborted[0] else out


def meet_closure_size(host_sets, cap):
    """Size of the intersection (meet) semilattice generated by host_sets
    = number of distinct non-empty intersections. This is the realistic
    IE term count after merging equal region-intersections. Returns
    (size, capped?) where capped means it exceeded `cap` and we stopped."""
    seen = set()
    frontier = []
    for h in host_sets:
        key = h
        if key not in seen:
            seen.add(key)
            frontier.append(h)
    # close under pairwise intersection
    work = list(frontier)
    while work:
        a = work.pop()
        for b in list(seen):
            c = a & b
            if c and c not in seen:
                seen.add(c)
                work.append(c)
                if len(seen) > cap:
                    return len(seen), True
    return len(seen), False


def region_ie_support(R0, H, s, cap_full):
    """Exact region-IE support if |H| <= cap_full (full subset IE);
    else None (too many hosts to enumerate the full alternating sum here;
    the meet-closure size still characterises the realistic cost)."""
    r = len(R0)
    h = len(H)
    if h == 0:
        return 0
    if h > cap_full:
        return None
    total = 0
    Hl = list(H)
    for k in range(1, h + 1):
        sign = 1 if k % 2 == 1 else -1
        for A in itertools.combinations(Hl, k):
            inter = A[0]
            for M in A[1:]:
                inter = inter & M
            # R0 subset inter always (every M in H contains R0)
            extra = len(inter) - r
            if extra >= s - r:
                total += sign * comb(extra, s - r)
    return total


def ground_truth_support(R0, adj, s):
    """Count s-cliques containing R0 by enumerating (s-r)-cliques in the
    common neighbourhood of R0. Exact; feasible on small graphs / small
    s-r."""
    common = set(adj[next(iter(R0))])
    for v in R0:
        common &= adj[v]
    common -= set(R0)
    need = s - len(R0)
    if need == 0:
        return 1
    cand = sorted(common)
    cnt = 0
    # enumerate need-subsets of cand that are cliques
    def rec(start, chosen):
        nonlocal cnt
        if len(chosen) == need:
            cnt += 1
            return
        for i in range(start, len(cand)):
            v = cand[i]
            if all(v in adj[c] for c in chosen):
                rec(i + 1, chosen + [v])
    rec(0, [])
    return cnt


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("graph")
    ap.add_argument("r", type=int)
    ap.add_argument("s", type=int)
    ap.add_argument("--sample", type=int, default=200)
    ap.add_argument("--no-correctness", action="store_true")
    ap.add_argument("--mce-budget", type=float, default=120.0)
    ap.add_argument("--cap-full-ie", type=int, default=18)
    ap.add_argument("--cap-closure", type=int, default=200000)
    ap.add_argument("--seed", type=int, default=20260618)
    args = ap.parse_args()
    random.seed(args.seed)

    adj = load_graph(args.graph)
    n = len(adj)
    m = sum(len(a) for a in adj.values()) // 2
    print(f"[probe] {args.graph}: n={n} m={m}  (r,s)=({args.r},{args.s})", flush=True)

    t0 = time.time()
    mcs = maximal_cliques(adj, args.s, args.mce_budget)
    if mcs is None:
        print(f"[probe] maximal-clique enumeration exceeded "
              f"{args.mce_budget}s budget; skip (use binary overlap stats).")
        return
    print(f"[probe] regions (maximal cliques >= s): {len(mcs)} in "
          f"{time.time()-t0:.1f}s", flush=True)
    if not mcs:
        print("[probe] no region of size >= s; nothing to test.")
        return

    # vertex -> set of region ids containing it
    vtx_regions = {}
    for i, M in enumerate(mcs):
        for v in M:
            vtx_regions.setdefault(v, set()).add(i)

    # sample r-cliques: pick a random region, pick a random r-subset of it
    samples = []
    tries = 0
    big = [M for M in mcs if len(M) >= args.r]
    while len(samples) < args.sample and tries < args.sample * 50 and big:
        tries += 1
        M = random.choice(big)
        R0 = frozenset(random.sample(sorted(M), args.r))
        samples.append(R0)

    n_ok = n_bad = 0
    hostszs = []
    closures = []
    closure_capped = 0
    ie_none = 0
    for R0 in samples:
        # host maximal cliques of R0 = regions containing all r vertices
        host_ids = set.intersection(*(vtx_regions[v] for v in R0))
        H = [mcs[i] for i in host_ids]
        hostszs.append(len(H))
        cl, capped = meet_closure_size(H, args.cap_closure)
        closures.append(cl)
        if capped:
            closure_capped += 1
        if not args.no_correctness:
            ie = region_ie_support(R0, H, args.s, args.cap_full_ie)
            if ie is None:
                ie_none += 1
                continue
            gt = ground_truth_support(R0, adj, args.s)
            if ie == gt:
                n_ok += 1
            else:
                n_bad += 1
                if n_bad <= 5:
                    print(f"  MISMATCH R0={sorted(R0)} IE={ie} truth={gt} "
                          f"|H|={len(H)}")

    def dist(xs):
        xs = sorted(xs)
        if not xs:
            return "n/a"
        k = len(xs)
        return (f"min={xs[0]} med={xs[k//2]} "
                f"p95={xs[min(k-1,int(0.95*k))]} max={xs[-1]} mean={sum(xs)/k:.1f}")

    print(f"[probe] |Host| (max cliques per r-clique): {dist(hostszs)}")
    print(f"[probe] meet-closure size (realistic IE terms): {dist(closures)}"
          + (f"  [{closure_capped} capped > {args.cap_closure}]" if closure_capped else ""))
    if not args.no_correctness:
        tested = n_ok + n_bad
        print(f"[probe] CORRECTNESS: {n_ok}/{tested} region-IE == direct "
              f"enumeration"
              + (f"  ({ie_none} skipped: |H|>{args.cap_full_ie})" if ie_none else ""))
        print("[probe] VERDICT: " + ("region-IE is EXACT here."
              if n_bad == 0 and tested > 0 else
              ("region-IE MISMATCHES — bug or wrong formula." if n_bad else
               "no cell tested (all skipped).")))


if __name__ == "__main__":
    main()
